name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 23
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Build
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test
        continue-on-error: true

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4.4.3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin